import registerComponent from './registerComponent';

import MenuItem from '../components/MenuItem';
import PasswordItems from '../pages/Profile/components/ProfileItem/PasswordItems';
import Loader from '../components/Loader';
import IconButton from '../components/Buttons/IconButton';
import FormInput from '../components/Inputs/FormInput';
import Form from '../components/Forms/Form';
import ErrorMessage from '../components/ErrorMessage';
import Avatar from '../components/Avatar';
import Content from '../components/Content';
import ImagePreview from '../components/ImagePreview';
import Info from '../components/Info';
import ImageInput from '../components/Inputs/ImageInput';
import TextInput from '../components/Inputs/TextInput';
import MembersModal from '../components/MembersModal';
import FilesMenu from '../components/Menu/FilesMenu';
import MembersMenu from '../components/Menu/MembersMenu';
import Message from '../components/Message';
import ChatsBody from '../pages/Chats/components/ChatsBody';
import ChatsFooter from '../pages/Chats/components/ChatsFooter';
import ChatsHeader from '../pages/Chats/components/ChatsHeader';
import ChatsItem from '../pages/Chats/components/ChatsItem';
import ChatsList from '../pages/Chats/components/ChatsList';
import ChatsSpace from '../pages/Chats/components/ChatsSpace';
import ChatsPanel from '../pages/Chats/components/ChatsPanel';
import WithoutChat from '../pages/Chats/components/WithoutChat';
import ChatsModal from '../pages/Chats/components/ChatsModal';
import ProfileItem from '../pages/Profile/components/ProfileItem';
import ProfileBody from '../pages/Profile/components/ProfileBody';
import ProfileFooter from '../pages/Profile/components/ProfileFooter';
import ProfileHeader from '../pages/Profile/components/ProfileHeader';
import Button from '../components/Buttons/Button';
import Input from '../components/input';
import Chat from '../pages/Chats/components/Chat';
import FormWithoutButtons from '../components/Forms/FormWithoutButtons';
import ChatInfo from '../pages/Chats/components/ChatInfo';
import MembersAddItem from '../components/MembersAddItem';
import MembersRemoveItem from '../components/MembersRemoveItem';
import UploadButton from '../components/ImagePreview/components/UploadButton';
import RemoveButton from '../components/ImagePreview/components/RemoveButton';
import FilesInput from '../components/Inputs/ImageInput/components/FilesInput/FilesInput';

import AddIcon from '../components/icons/Add';
import EllipsisVerticalIcon from '../components/icons/EllipsisVertical';
import ExitIcon from '../components/icons/Exit';
import FileIcon from '../components/icons/File';
import HandIcon from '../components/icons/Hand';
import ImageIcon from '../components/icons/Image';
import LeftArrowIcon from '../components/icons/LeftArrow';
import LocationIcon from '../components/icons/Location';
import LockIcon from '../components/icons/Lock';
import OtterIcon from '../components/icons/Otter';
import PaperclipIcon from '../components/icons/Paperclip';
import PenIcon from '../components/icons/Pen';
import PencilIcon from '../components/icons/Pencil';
import PhotoIcon from '../components/icons/Photo';
import RemoveIcon from '../components/icons/Remove';
import SearchIcon from '../components/icons/Search';
import TrashIcon from '../components/icons/Trash';

const registerComponents = () => {
  registerComponent('FilesInput', FilesInput);
  registerComponent('RemoveButton', RemoveButton);
  registerComponent('UploadButton', UploadButton);
  registerComponent('MembersRemoveItem', MembersRemoveItem);
  registerComponent('MembersAddItem', MembersAddItem);
  registerComponent('ChatInfo', ChatInfo);
  registerComponent('MenuItem', MenuItem);
  registerComponent('PasswordItems', PasswordItems);
  registerComponent('Loader', Loader);
  registerComponent('FormWithoutButtons', FormWithoutButtons);
  registerComponent('Button', Button);
  registerComponent('IconButton', IconButton);
  registerComponent('Input', Input);
  registerComponent('FormInput', FormInput);
  registerComponent('Form', Form);
  registerComponent('ErrorMessage', ErrorMessage);
  registerComponent('Avatar', Avatar);
  registerComponent('Content', Content);
  registerComponent('ImagePreview', ImagePreview);
  registerComponent('Info', Info);
  registerComponent('ImageInput', ImageInput);
  registerComponent('TextInput', TextInput);
  registerComponent('MembersModal', MembersModal);
  registerComponent('FilesMenu', FilesMenu);
  registerComponent('MembersMenu', MembersMenu);
  registerComponent('Message', Message);
  registerComponent('ChatBody', ChatsBody);
  registerComponent('Chat', Chat);
  registerComponent('ChatFooter', ChatsFooter);
  registerComponent('ChatHeader', ChatsHeader);
  registerComponent('ChatItem', ChatsItem);
  registerComponent('ChatList', ChatsList);
  registerComponent('ChatSpace', ChatsSpace);
  registerComponent('ChatsPanel', ChatsPanel);
  registerComponent('WithoutChat', WithoutChat);
  registerComponent('Modal', ChatsModal);
  registerComponent('ProfileItem', ProfileItem);
  registerComponent('ProfileBody', ProfileBody);
  registerComponent('ProfileFooter', ProfileFooter);
  registerComponent('ProfileHeader', ProfileHeader);
  registerComponent('AddIcon', AddIcon);
  registerComponent('EllipsisVerticalIcon', EllipsisVerticalIcon);
  registerComponent('ExitIcon', ExitIcon);
  registerComponent('FileIcon', FileIcon);
  registerComponent('HandIcon', HandIcon);
  registerComponent('ImageIcon', ImageIcon);
  registerComponent('LeftArrowIcon', LeftArrowIcon);
  registerComponent('LocationIcon', LocationIcon);
  registerComponent('LockIcon', LockIcon);
  registerComponent('OtterIcon', OtterIcon);
  registerComponent('PaperclipIcon', PaperclipIcon);
  registerComponent('PenIcon', PenIcon);
  registerComponent('PencilIcon', PencilIcon);
  registerComponent('PhotoIcon', PhotoIcon);
  registerComponent('RemoveIcon', RemoveIcon);
  registerComponent('SearchIcon', SearchIcon);
  registerComponent('TrashIcon', TrashIcon);
};

export default registerComponents;
